# Generated by Django 6.0.4 on 2026-04-18 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe_name', models.CharField(blank=True, max_length=120)),
                ('is_planning_event', models.BooleanField(blank=True, null=True)),
                ('event_preferences', models.JSONField(default=list)),
                ('tribe_vibe', models.JSONField(default=list)),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('travel_preference', models.CharField(blank=True, max_length=50)),
                ('priorities', models.JSONField(default=list)),
                ('availability_days', models.IntegerField(default=2)),
                ('event_frequency', models.IntegerField(default=2)),
                ('group_size', models.IntegerField(default=10)),
                ('completed_step', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('avatar_color', models.CharField(default='#E76F51', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🔥', max_length=10)),
                ('icon_bg', models.CharField(default='#FDBA9A', max_length=20)),
                ('category', models.CharField(choices=[('food', 'Food & Drink'), ('art', 'Art & Culture'), ('outdoors', 'Outdoors'), ('music', 'Live Music'), ('wellness', 'Wellness'), ('books', 'Books & Talks'), ('comedy', 'Comedy & Shows'), ('tech', 'Tech & Ideas'), ('travel', 'Travel & Trips'), ('social', 'Social')], default='social', max_length=30)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tribes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('creator', 'Creator')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tribes.tribe')),
            ],
            options={
                'unique_together': {('user', 'tribe')},
            },
        ),
    ]
